"""Fibonacci even-only sum sequence.

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""


def _fibo_gen(n: int = 10):
    assert n > 0
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b


def _find_max_fibo_steps(max_value, start):
    i = start

    while True:
        series = _fibo_gen(i)
        if max(series) > max_value:
            return i - 1
        else:
            i += 1


def sum_even_fibo(max_value: int = 100, start: int = 1):
    max_steps = _find_max_fibo_steps(max_value, start)

    evens = []
    for i in _fibo_gen(max_steps):
        if i % 2 == 0:
            evens.append(i)

    return sum(evens)


result = sum_even_fibo(4_000_000)
print(result)
